parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\UrlShortener: ~

    App\Repository\ShortUrlRepository: ~
    
    App\Validator\Constraints\ValidUrlValidator:
        tags: ['validator.constraint_validator']
